version: 2.1

jobs:
  checkout_and_unit_test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: "Run Unit Tests"
          command: echo "Running unit tests..."

  deploy_backend:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Deploy Backend"
          command: echo "Deploying backend..."

  integration_tests_backend:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Run Integration Tests"
          command: echo "Running integration tests..."

  deploy_staging:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Deploy Staging"
          command: echo "Deploying to staging..."

  acceptance_tests:
    parameters:
      test_number:
        type: integer
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Run Acceptance Test << parameters.test_number >>"
          command: |
            echo "Running acceptance test #<< parameters.test_number >>"

  deploy_production:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Deploy Production"
          command: echo "Deploying to production..."

workflows:
  version: 2
  monWorkflow:
    jobs:
      - checkout_and_unit_test
      - deploy_backend:
          requires:
            - checkout_and_unit_test
      - integration_tests_backend:
          requires:
            - deploy_backend
      - deploy_staging:
          requires:
            - integration_tests_backend
      - acceptance_tests:
          requires:
            - deploy_staging
          matrix:
            parameters:
              test_number: [1, 2, 3, 4]
      - deploy_production:
          requires:
            - acceptance_tests
