version: 2.1

jobs:
  checkout_and_unit_test:
    description: Checkout code and run unit tests
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: "Run Unit Tests"
          command: echo "Running unit tests..."

  deploy_backend:
    description: Deploy backend
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Deploy Backend"
          command: echo "Deploying backend..."

  integration_tests_backend:
    description: Run integration tests
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Run Integration Tests"
          command: echo "Running integration tests..."

  deploy_staging:
    description: Deploy to staging environment
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Deploy to Staging"
          command: echo "Deploying to staging..."

  acceptance_tests:
    description: Run acceptance tests
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Run Acceptance Tests"
          command: echo "Running acceptance tests..."

  deploy_production:
    description: Deploy to production
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Deploy to Production"
          command: echo "Deploying to production..."

workflows:
  version: 2
  monWorkflow:
    jobs:
      - checkout_and_unit_test
      - deploy_backend:
          requires:
            - checkout_and_unit_test
      - integration_tests_backend:
          requires:
            - deploy_backend
      - deploy_staging:
          requires:
            - integration_tests_backend
      - acceptance_tests:
          requires:
            - deploy_staging
          matrix:
            parameters:
              test_number: [1, 2, 3, 4]
      - deploy_production:
          requires:
            - acceptance_tests